spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boostim?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true
    username: root
#    password: mysql

authserver:
  url: http://localhost:9000

appserver:
  url: "*"

webserver:
  url: http://localhost:8080